apiVersion: v1
kind: Service
metadata:
  name: demo-replicaset-0-nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
  - protocol: TCP
    nodePort: 30017
    port: 27017
  selector:
    statefulset.kubernetes.io/pod-name: demo-replicaset-0
  type: NodePort